# Site settings
title: 彭芊
subtitle: Misuqian
email: misuqian@gmail.com
description: 男生.热爱用代码去创造有趣产品.南方科技大学13级学生.腾讯实习生.女朋友叫米汤姐.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "http://pengqian.win" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
weibo_url: http://weibo.com/u/3789094183?is_all=1
steam_url: http://steamcommunity.com/id/misuqian
github_url: http://github.com/misuqian

# Build settings
markdown: kramdown
