#
###################################
# Site wide configuration
####################################
#
title: Misuqian
email: misuqian@gmail.com
description: 男生.热爱用代码去创造有趣产品.南方科技大学13级学生.腾讯实习生.女朋友叫米汤姐
url: http://pengqian.win
localse: cn


#
###################################
# Jekyll configuration
####################################
#
timezone:          China/Shenzhen
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: 彭芊
  avatar: misuqian.png
  job: iOS&Game Developer
  bio: 
  description: 男生.热爱用代码去创造有趣产品.南方科技大学13级学生.腾讯实习生.女朋友叫米汤姐.
  email:              misuqian@gmail.com
  #google.plus:       username
  #twitter:           username
  #facebook:          username
  github:             misuqian
  #stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
  #linkedin:          username
  #xing:              username
  #instagram:         username
  #lastfm:            username
  #tumblr:            username
  #pinterest:         username
  #foursquare:        username
  steam:              misuqian
  #dribbble:          username
  #youtube:           username
  #soundcloud:        username
  weibo:				u/3789094183
  #flickr:            username
  #codepen:           username
  #keybase:           username
  #xmpp:              username@server.com
  #hackernews:        username
  #behance:           username
